/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntentionalLeaderRouteImport } from './routes/intentional-leader'
import { Route as IndexRouteImport } from './routes/index'

const IntentionalLeaderRoute = IntentionalLeaderRouteImport.update({
  id: '/intentional-leader',
  path: '/intentional-leader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intentional-leader': typeof IntentionalLeaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intentional-leader': typeof IntentionalLeaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intentional-leader': typeof IntentionalLeaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/intentional-leader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/intentional-leader'
  id: '__root__' | '/' | '/intentional-leader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntentionalLeaderRoute: typeof IntentionalLeaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intentional-leader': {
      id: '/intentional-leader'
      path: '/intentional-leader'
      fullPath: '/intentional-leader'
      preLoaderRoute: typeof IntentionalLeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntentionalLeaderRoute: IntentionalLeaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
